version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
  gpio_poller:
    build: gpio
    environment:
      - DELAY=0.5
    container_name: gpio_poller
    restart: always
    volumes:
      - /dev:/dev
    depends_on:
      - mosquitto
    privileged: true
  hassio:
    image: homeassistant/amd64-hassio-supervisor
    container_name: hassio_supervisor
    restart: always
    privileged: true
    entrypoint: ["/bin/bash", "-c", "/scripts/start_hassio.sh"]
    security_opt:
      - seccomp:unconfined
    environment:
      - HOMEASSISTANT_REPOSITORY=homeassistant/qemux86-64-homeassistant
      - SUPERVISOR_SHARE=${SUPERVISOR_SHARE}
      - SUPERVISOR_NAME=hassio_supervisor
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
    volumes:
      - ${SUPERVISOR_SHARE}:/data
      - ./scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    depends_on:
      - mosquitto
