version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
  gpio_poller:
    build: gpio
    environment:
      - DELAY=0.5
    container_name: gpio_poller
    restart: always
    volumes:
      - /dev:/dev
    depends_on:
      - mosquitto
    privileged: true
  hassio:
    image: ghcr.io/home-assistant/amd64-hassio-supervisor
    container_name: hassio_supervisor
    restart: always
    privileged: true
    entrypoint: ["/bin/bash", "-c", "/scripts/start_hassio.sh"]
    security_opt:
      - seccomp:unconfined
    environment:
      - HOMEASSISTANT_REPOSITORY=homeassistant/qemux86-64-homeassistant
      - SUPERVISOR_SHARE=${SUPERVISOR_SHARE}
      - SUPERVISOR_NAME=hassio_supervisor
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
    volumes:
      - ${SUPERVISOR_SHARE}:/data
      - ./scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    depends_on:
      - mosquitto
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./ftp/data:/home/camera/
      - ./ftp/passwd:/etc/pure-ftpd/passwd
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: ${FTP_USERNAME}
      FTP_USER_PASS: ${FTP_PASSWORD}
      FTP_USER_HOME: /home/camera
    restart: always
  dropbox:
    image: rbonghi/dropbox:latest
    container_name: dropbox
    environment:
      - PYTHONUNBUFFERED=1
      - DROPBOX_APP_KEY=${DROPBOX_APP_KEY}
      - DROPBOX_APP_SECRET=${DROPBOX_APP_SECRET}
      - DROPBOX_REFRESH_TOKEN=${DROPBOX_REFRESH_TOKEN}
    volumes:
      - ./ftp/data:/dropbox
    restart: always
